export { default as ScrollToTop } from './ScrollToTop/ScrollToTop';
export { default as Section } from './Section/Section';
export { default as Header } from './Header/Header';
export { default as Hero } from './Hero/Hero';
export { default as Categories } from './Categories/Categories';
export {default as PopularCourses} from './PopularCourses/PopularCourses';
export { default as StudentsSay } from './StudentsSay/StudentsSay';
export { default as StudentsSayItem } from './StudentsSayItem/StudentsSayItem';
export { default as BecomeTeacher } from './BecomeTeacher/BecomeTeacher';
export {default as CourseItem} from './CourseItem/CourseItem';
export {default as ButtonBuy} from './ButtonBuy/ButtonBuy';
export {default as PreviewCourse} from './PreviewCourse/PreviewCourse';
export {default as SmallMediaCoursePreview} from './SmallMediaCoursePreview/SmallMediaCoursePreview';
export {default as LargeMediaCoursePreview} from './LargeMediaCoursePreview/LargeMediaCoursePreview';
export {default as CourseContent } from './CourseContent/CourseContent';
export {default as CourseInfo } from './CourseInfo/CourseInfo';
export {default as CourseBuySmallMedia } from './CourseBuySmallMedia/CourseBuySmallMedia';
export {default as List } from './List/List';
export {default as AboutInfo } from './AboutInfo/AboutInfo';
export {default as Form } from './Form/Form';
export {default as Back } from './Back/Back';
export {default as CategoryList } from './CategoryList/CategoryList';
export {default as PagesList } from './PagesList/PagesList';
export {default as SocialIcons } from './SocialIcons/SocialIcons';
export {default as WatchCourse} from '../component/WatchCourse/WatchCourse';
export {default as Accordin } from './Accordin/Accordin';
export {default as ProtectedRoute } from './ProtectedRoute/ProtectedRoute';
export {default as ContactSection } from './ContactSection/ContactSection';
export {default as EditProfile } from './EdiitProfile/EditProfile';
export {default as ProceedButton } from './ProceedButton/ProceedButton';
export {default as PaymentMethods } from './PaymentMethods/PaymentMethods';
export {default as Summary } from './Summary/Summary';
export {default as OrderDetail } from './OrderDetail/OrderDetail';
export {default as CheckBilling } from './CheckBilling/CheckBilling';
export {default as CheckOutHeader } from './CheckOutHeader/CheckOutHeader';
export {default as ViewProfile } from './ViewProfile/ViewProfile';
export {default as Alert } from './Alert/Alert';
export {default as AddNewInformation } from './AddNewInformation/AddNewInformation';
